### ISSUE TITLE
cleanup 3rd-party assets

### ISSUE THREAD

**Issue by truemoroz** [barrel/shopify-vite#120]
Look at docs https://shopify-vite.barrelny.com/guide/troubleshooting.html#how-to-cleanup-the-assets-folder
You mention this plugin https://www.npmjs.com/package/@by-association-only/vite-plugin-shopify-clean
But it doesn't support vite 5. And it seems like author is not going to do anything with it

May be this plugin would be better for this purpose
https://github.com/knjshimi/shopify-vite/tree/main/packages/vite-plugin-shopify-assets

**Comment by knjshimi** [comment]
Hi @truemoroz, I developed the vite-plugin-shopify-assets for that reason. The other plugin wasn't compatible with vite 5.

On top of that, vite-plugin-copy doesn't work on dev mode, and the plugin author said it's not a focus for them.

So in the end, vite-plugin-shopify-assets should cover everything that plugin copy and vite plugin cleanup do.

The only thing to keep in mind is that I haven't really put it in production for a long time. I'm starting to use it in my agency this week - so far so good!

If you want to give it a try and send me your feedback, I'd appreciate it. If you want to look at the code and think it could be better, let me know as well.

Thanks!

**Comment by knjshimi** [comment]
Hey @montalvomiguelo, do you think you could have a deeper look at my plugin to give some feedback?

I understand if you don't have enough time.

**Comment by montalvomiguelo** [comment]
I'll take a look this weekend @knjshimi :)

**Comment by montalvomiguelo** [comment]
Hi @knjshimi :)

I created this little [example on Stackblitz](https://stackblitz.com/edit/vitejs-vite-ixzvmx?file=vite.config.js). We have a typical Shopify theme folder structure because, let’s say, we need to keep things simple and working with the Shopify GitHub Integration.

Could vite-plugin-shopify-assets clean up the stuff that Vite generates without affecting other files in the assets/ directory? Ideally, with zero configuration, it’s nice for developers when things [work out of the box](https://stackblitz.com/edit/vitejs-vite-xufora?file=vite.config.js).

Let’s say we don’t need to do any copy operations in the example. Is there a way that behavior can be extracted into its plugin?

**Comment by knjshimi** [comment]
Hey @montalvomiguelo thanks for looking into it!

I definitely put some default config in place, and it's possible to define if it should copy or not depending on the vite mode (build, watch, serve).

Let me do some testing when no configuration is set, and I will get back to you.

**Comment by knjshimi** [comment]
Hey @montalvomiguelo, I have just published a release (0.1.5) that fixes a few bugs when inferring default options. [Here's a fork of your Stackblitz example](https://stackblitz.com/edit/vitejs-vite-gjfyho?file=package.json) with the latest release. I hope that one works better!

Note: **Don't pass `build: { emptyOutDir: false }`**

The plugin will take care of (and honour) that vite build option, meaning:
- If it's `false`, it will not attempt to clear it.
- If it's `true`, the plugin will under the hood turn that option to `false`, and do the cleanup itself based on the manifest.

Let me know how it goes :)

**Comment by montalvomiguelo** [comment]
@knjshimi  In the original example, we have a very important asset, [my-random-widget.js](https://stackblitz.com/edit/vitejs-vite-ixzvmx?file=assets%2Fmy-random-widget.js), that guy should not be deleted. 

Actual:
<img width="495" alt="Screenshot 2024-04-05 at 8 16 56 AM" src="https://github.com/barrel/shopify-vite/assets/5134470/15f080c9-0513-427e-86b8-6b004ce57dbd">

**Comment by knjshimi** [comment]
@montalvomiguelo, at the moment this is the minimum configuration that we need to make it work:

<img width="500" alt="Screenshot 2024-04-05 at 11 26 35 PM" src="https://github.com/barrel/shopify-vite/assets/111416569/f84da58d-f8a2-4fcb-ae3b-a566e3c69b05">
<br><br>

It assumes:
- `public/` folder that holds static assets
- `assets/` folder for final shopify assets
- `targets: [*]` plugin option

I'll see if there's an easy way to:
- not require targets
- use a single `assets/` folder as both source and destination... but I'm struggling to see this working to be honest.

**Comment by knjshimi** [comment]
Hey @truemoroz, can you give me an idea of what you were expecting from that plugin (either vite-plugin-shopify-clean or vite-plugin-shopify-assets)? I want to understand your use case and likely folder structure.

Based on what we discussed in this thread so far, what are your thoughts?

**Comment by knjshimi** [comment]
Quick update: I think I found a way, which is more elegant and would solve the issue. It's likely to be more performant too.

It will take some time, but I'll let you know once it's done ☺️

**Comment by truemoroz** [comment]
I want to keep my assets in target folder after rebuilding app

**Comment by knjshimi** [comment]
Hi @truemoroz, in that case vite-plugin-shopify-assets should do the trick. I have updated the readme with new documentation for zero config. Let me know if you are able to make it work with your folder structure ☺️


@montalvomiguelo I wasn't able to make it work without using a separate static assets folder. It won't be possible because I can't find a way to differentiate old build files from static assets if they live in the same folder.

**Comment by montalvomiguelo** [comment]
@knjshimi, the [code](https://github.com/dan-gamble/vite-plugin-shopify-clean) of the previous plugin is public now 🎉 It contains a couple of ideas that your plugin could reference? 

It'd be great to keep things simpler to help a wider range of projects like the one provided above that only need a simple way to clean up assets generated by Vite while preserving any other file that might be added by apps or via theme editor.

**Comment by knjshimi** [comment]
Hi @montalvomiguelo, thanks for that :) I will have a look and see if there's something I could adapt.

**Comment by knjshimi** [comment]
I still need to take a deeper look, but I can see a potential issue.

It differentiates old build files from by matching a glob pattern like 'name-*.ext', which mimics the default chunkFileNames pattern in vite '[name]-[hash].[ext]'

What if users use a different pattern via Vite options, eg: '-[name]__[hash].[ext]'?

What if users have two similar files in the same folder - one static and one processed? Eg: style-random.css and style-HuTrDF.css

I tried a similar path, at least in theory, in my recent experiments with no success because of the second case (the first one is not hard to overcome).

But maybe there is some small implementation detail in his method that I'm missing. I will give it another shot.

**Comment by knjshimi** [comment]
@montalvomiguelo do you have any idea why there is a check for "process.env.VITE_WATCH" on vite-plugin-shopify-clean?

I thought it was passed on vite watch mode, but it isn't (the correct way is this.meta.watchMode). Maybe it's a custom BAO thing?

Ideally we want this cleanup to work on watch mode as well.

**Comment by knjshimi** [comment]
Hey @montalvomiguelo maybe you want to close this issue now that vite-plugin-shopify-clean supports vite 5. cc: @truemoroz 

I will still continue working on vite-plugin-shopify-assets anyway, and see if I can solve that use case you pointed out to me.

I got it working, at least partially, but I don't fully understand why yet. And I want to make sure it works on all modes (dev, build, watch) and it includes the copy feature.

Thanks for the help so far! Greatly appreciated 😄
