### ISSUE TITLE
version 0.0.6 and up of vite-plugin-shopify-modules no longer creating symlinks

### ISSUE THREAD

**Issue by andyxmas** [barrel/shopify-vite#60]
Firstly, this set of vite plugins, the seed theme, and the support you're offering on issues is fantastic - thank you so much!

I've been using version `0.0.4` of `vite-plugin-shopify-modules` for the last few months to great success. I've just updated `vite-plugin-shopify` to the latest version with no issues, I but I've found that each version after `0.0.5` of the modules plugin breaks the functionality for me.

## What happens in 0.0.5
With vite running, I do the following in vscode:

 - create a section called `test.liquid` 
 - create a directory within the modules directory called `test`
 
Result: Near instantly there is a `test.section.liquid` file showing in the `modules/test` dir

## in versions > = 0.0.6
 - steps as above

Result: `test.section.liquid` is NOT created 

by running `npx vite -d` I see output like this:

> vite:hmr [file change] sections/test7.liquid +6s
> vite:hmr [no modules matched] sections/test7.liquid +0ms

I've briefly tested with snippets, and with creating the `test.section.liquid` in the module first but neither working as expected.

## my setup

I simplified by setup down when testing, and the issue presents with this setup

```
import { defineConfig } from 'vite';
import viteShopify from 'vite-plugin-shopify';
import viteShopifyModules from 'vite-plugin-shopify-modules';

export default defineConfig({
  plugins: [
    viteShopify({
      themeRoot: './',
      sourceCodeDir: 'src',
      entrypointsDir: 'src/entrypoints',
      additionalEntrypoints: ['modules/**/*.(js|scss)']
    }),
    viteShopifyModules()
  ]
});
`

other module versions
```
    "vite": "^4.0.4",
    "vite-plugin-shopify": "^1.0.2"
```

node version 18.15.0
OSX 13.2.1

**Comment by andyxmas** [comment]
note, I also find the same if I run  the vite-shopify-example theme

**Comment by montalvomiguelo** [comment]
@andyxmas, thank you so much for your help and support on this project 🙏 🙏 

_That behavior in 0.0.4 is probably a bug/feature, lol._

The original intention here was to work from the module folders, creating .section.liquid or .snippet.liquid files so that the plugin can do two things:

* Move the files to their corresponding directory in the theme without the .section or. snippet extension _(Target files)_
* Create symlinks from the .section.liquid or .snippet.liquid files to the Target files

I have been chatting about this plugin with my team at Barrel; it adds unnecessary complexity to themes.

Keeping our sections and snippets where they should be is easy enough without cluttering the project structure with many symlink files, making the theme structure confusing and hard to maintain. 

We think It's best to deprecate this plugin in a future release to keep things simple and provide a better development experience.

**Comment by andyxmas** [comment]
thanks @montalvomiguelo - I understand the reasons here. Will discuss this with my team as well. 

One thought - may worth calling out in the change log for https://github.com/barrel/shopify-vite/pull/62 that adding the below to vite config should mean that your theme will continue to work as expected after removing `vite-plugin-shopify-modules`

```
  resolve: {
    alias: {
      '@modules': './modules'
    }
  },
```

**Comment by montalvomiguelo** [comment]
Thanks for bringing that up, @andyxmas! We'll consider this for the change log. Appreciate your insight! 🙏
