### ISSUE TITLE
Additional attribute in render

### ISSUE THREAD

**Issue by truemoroz** [barrel/shopify-vite#98]
How can I render such strings?
```html
<script id="EnableZoomOnHover-featured" src="{{ 'magnify.js' | asset_url }}" defer="defer"></script>
<link rel="stylesheet" href="{{ 'component-list-menu.css' | asset_url }}" media="print" onload="this.media='all'">
```
I think it's important feature

**Comment by Eben-Hafkamp** [comment]
@truemoroz You can render them however the assets folder is treated as distribution because of the limitations of the folder structure accepted by Shopify. I think the solution is to use a public directory to handle assets at build time, here is a link to the thread I think you are after: https://github.com/barrel/shopify-vite/issues/68

**Comment by truemoroz** [comment]
@Eben-Hafkamp 
It's good but it's not exactly what I need. I need additional attributes for my own js file, not 3d-party.

**Comment by vdloc** [comment]
Same here, We need to render script/stylesheet tag with attributes like "defer/async" for js and "media/onload callback" for stylesheets
